typography_spectrum: 0.4724492453970015
content_rating:
  adult: false
color:
  brandStrength: 0.25519323884509504
  lightness: 0.16940784873440862
  saturation: 0.4076715155970305
  rhythmicContrast: 0.3198960996232927
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4166612478438765
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/394d628e-b4e0-4677-ba84-4938c7bd73e0.png
name: Tiny Buffalo Design
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3da78ed7-fd09-4129-8538-1fd18131c232.png
title: ''
description: 'PROFESSIONAL STANDARD, LOW COST.'
