typography_spectrum: 0.29194343625567853
content_rating:
  adult: false
color:
  brandStrength: 0.7342769943643361
  lightness: 0.9357507689855993
  saturation: 0.6886711448896676
  rhythmicContrast: 0.7912520268000662
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.7836486208252609
author:
  name: ''
  email: ''
  url: ''
logo: null
name: Tiny Buffalo Design
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3da78ed7-fd09-4129-8538-1fd18131c232.png
title: GRAPHIC DESIGN
description: 'PROFESSIONAL STANDARD, LOW COST.'
