typography_spectrum: 0.29194343625567853
content_rating:
  adult: false
color:
  brandStrength: 0.7342769943643361
  lightness: 0.9357507689855993
  saturation: 0.6886711448896676
  rhythmicContrast: 0.7912520268000662
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.7836486208252609
author:
  name: Felix Collier
  email: felix@tinybuffalodesign.co.uk
  url: www.tinybuffalodesign.co.uk
logo: null
name: Tiny Buffalo Design
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b716b6ee-4cd8-4149-8670-3af24cb162fb.png
title: GRAPHIC DESIGN
description: 'PROFESSIONAL STANDARD, LOW COST.'
