typography_spectrum: 0.3222787263803184
content_rating:
  adult: false
color:
  brandStrength: 0.8929145284928381
  lightness: 0.32807521033100784
  saturation: 0.23894648882560432
  rhythmicContrast: 0.13118435442447662
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.7464340007863939
author:
  name: ''
  email: ''
  url: ''
logo: null
name: Tiny Buffalo Design
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3da78ed7-fd09-4129-8538-1fd18131c232.png
title: TINY BUFFALO DESIGN
description: 'PROFESSIONAL STANDARD, LOW COST.'
